# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Build and deploy ASP.Net Core app to Azure Web App - SportClubsChallengesAPI

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
      
    - name: 'Clean nuget cache'
      run: dotnet clean ./SportClubsChallenges.sln --configuration ReleaseApi && dotnet nuget locals all --clear

    - name: Build with dotnet
      run: dotnet build --configuration ReleaseApi

    - name: dotnet publish
      run: dotnet publish -c ReleaseApi -o ${{env.DOTNET_ROOT}}/myapp

    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: SportClubsChallengesAPI
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_5556FBEE83BC4A729A8EB49745B4F3DA }}
        package: ${{env.DOTNET_ROOT}}/myapp

